# Generated by Django 4.2.7 on 2024-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True)),
                ('Number_type', models.CharField(choices=[('Home', 'Home'), ('Mobile', 'Mobile'), ('Office', 'Office')], max_length=200, null=True)),
            ],
        ),
    ]
