# Generated by Django 4.2.7 on 2024-04-29 09:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
