# Generated by Django 4.2.7 on 2024-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=models.IntegerField(null=True),
        ),
    ]
