# Generated by Django 4.2.7 on 2024-04-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.phone'),
        ),
        migrations.AddField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
    ]
