# Generated by Django 4.2.7 on 2024-04-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_socialmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='Social_Media',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='person',
            new_name='Person',
        ),
    ]
