# Generated by Django 4.2.7 on 2024-04-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_socialmedia_social_media_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Media',
            new_name='SocialMedia',
        ),
    ]
