# Generated by Django 4.2.7 on 2024-04-30 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_social_media_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
    ]
