# Generated by Django 4.2.7 on 2024-04-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_email_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Person',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='Person',
        ),
        migrations.AddField(
            model_name='person',
            name='Phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.phone'),
        ),
    ]
