# Generated by Django 4.2.7 on 2024-04-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_email_person_remove_phone_person_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Phone',
        ),
        migrations.AddField(
            model_name='email',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
        migrations.AddField(
            model_name='phone',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
    ]
