# Generated by Django 4.2.7 on 2024-04-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_person_email_remove_person_phone_email_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Person',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='Person',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.email'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.phone'),
        ),
    ]
