# Generated by Django 4.2.7 on 2024-04-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_email_person_remove_phone_person_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.socialmedia'),
        ),
    ]
