# Generated by Django 4.2.7 on 2024-05-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_email_phone_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Address_type',
        ),
    ]
