# Generated by Django 4.2.7 on 2024-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_email_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=200, null=True),
        ),
    ]
