# Generated by Django 4.2.7 on 2024-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='phone',
        ),
        migrations.AlterField(
            model_name='address',
            name='Address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('College', 'College')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Number_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Mobile', 'Mobile'), ('Office', 'Office'), ('College', 'College')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='Linked_App',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Linkdin', 'Linkdlin'), ('Snapchat', 'Snapchat'), ('WeChat', 'WeChat'), ('Discord', 'Discord')], max_length=200, null=True),
        ),
    ]
